---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: mibs_PR
  image: plugins/docker
  settings:
    build_args:
    - BRANCH=${DRONE_BRANCH}
    dry_run: true
    registry: docker.io
    repo: ciscocx/mibs
  when:
    event:
    - pull_request
    ref:
    - refs/heads/master
    - refs/tags/*

- name: mibs
  image: plugins/docker
  settings:
    auto_tag: true
    build_args:
    - BRANCH=master
    registry: docker.io
    repo: ciscocx/mibs
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - refs/tags/*

- name: send_notification
  image: plugins/slack
  settings:
    channel: drone-ci
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-64.png
    username: Drone CI
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - failure
---
kind: signature
hmac: 5510e58c3dd20edd7a69c679dc140a6c362eaa5e1b0b9e83296922d9d86221d8

...
